server:
  port: 8200
  servlet:
    context-path: "/"
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost:3306}/${MYSQL_DB:codewr_com}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USER_CWR:root}
    password: ${PASS_CWR:}
slack:
  webhook:
    url-monitor: https://hooks.slack.com/services/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
    channel: ${CHANEL_MONITOR:#check-info-2024}
    username: ${CHANEL_USERNAME:BOT}
    phut: ${PHUT:80}
    odd: ${ODD:2.0}
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsYW5ndWFnZUNvZGUiOiJ2aSIsImN1cnJlbmN5UmF0ZSI6MSwiY3VycmVuY3lSYXRlZXVyIjoxLCJjdXN0b21lckxpbWl0cyI6W10sImN1c3RvbWVyVHlwZSI6ImFub24iLCJjdXJyZW5jeUNvZGUiOiJVU0QiLCJjdXJyZW5jeUNvZGVBbm9uIjoiIiwiY3VzdG9tZXJJZCI6LTEsImJldHRpbmdWaWV3IjoiRXVyb3BlYW4gVmlldyIsInNvcnRpbmdUeXBlSWQiOjAsImJldHRpbmdMYXlvdXQiOjIsImRpc3BsYXlUeXBlSWQiOjEsInRpbWV6b25lSWQiOjIwLCJhdXRvVGltZVpvbmUiOjEsImxhc3RJbnB1dFN0YWtlIjowLCJldU9kZHNJZCI6IjQiLCJhc2lhbk9kZHNJZCI6IjQiLCJrb3JlYW5PZGRzSWQiOiIxIiwiaW50VGFiRXhwYW5kZWQiOjEsImRvbWFpbklEIjo0NzIsImFnZW50SUQiOjIzOTAwMzQ5LCJzaXRlSWQiOjIwMDkxLCJzZWxlY3RlZE9wdGlvbklkIjowLCJjdXN0b21lckxldmVsIjowLCJpYXQiOjE3MTg4NzgyNTV9.TZj9yFjvMVCmCYsry2MXYf_RJP3Qp2JYYv0EYX2-Wxo
    cookie: session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjotMSwiZXhwaXJlZERhdGUiOjE3MTg5NjUzMDE1NDYsImlhdCI6MTcxODg3ODI1NX0.CV0t3ZZE3rEnswMnD0ckwgOepol57ucoROiXPO0RTR8

